# Generated by Django 5.0.2 on 2024-02-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='lab/film/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
