# Generated by Django 5.0.2 on 2024-03-01 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_imgstackerpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imgstackerpost',
            options={'managed': False},
        ),
    ]
