# Generated by Django 5.0.2 on 2024-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_songqrpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCutsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='lab/NCuts/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
