# Generated by Django 5.0.2 on 2024-03-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='sharepage/ourImages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
