# Generated by Django 5.0.2 on 2024-03-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharepage', '0002_ourpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
